
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HaberPortali.Models
{

using System;
    using System.Collections.Generic;
    
public partial class comment
{

    public int comId { get; set; }

    public int comUserId { get; set; }

    public string comContent { get; set; }

    public System.DateTime comDate { get; set; }

    public int comNewsId { get; set; }



    public virtual newsInfo newsInfo { get; set; }

    public virtual userInfo userInfo { get; set; }

}

}
