
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HaberPortali.Models
{

using System;
    using System.Collections.Generic;
    
public partial class newsInfo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public newsInfo()
    {

        this.comment = new HashSet<comment>();

    }


    public int newsId { get; set; }

    public string newsTitle { get; set; }

    public string newsContent { get; set; }

    public string newsImage { get; set; }

    public System.DateTime newsDate { get; set; }

    public int newsCatId { get; set; }

    public int newsCreatedBy { get; set; }



    public virtual category category { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<comment> comment { get; set; }

    public virtual userInfo userInfo { get; set; }

}

}
