
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HaberPortali.Models
{

using System;
    using System.Collections.Generic;
    
public partial class userInfo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public userInfo()
    {

        this.comment = new HashSet<comment>();

        this.newsInfo = new HashSet<newsInfo>();

    }


    public int userId { get; set; }

    public string userName { get; set; }

    public string userMail { get; set; }

    public string userPw { get; set; }

    public int userAdmin { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<comment> comment { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<newsInfo> newsInfo { get; set; }

}

}
